import { useEffect, useState } from "react";
import { audienceSuggestions } from "./audienceRules";
import { demoUrl, inferDomain, parseDemoState } from "./demoState";
import type { DemoState, DemoView } from "./demoTypes";
const markets = [{id:"KR",label:"South Korea"},{id:"US",label:"United States"},{id:"JP",label:"Japan"},{id:"GLOBAL",label:"Global"}] as const;
export function useDemoState(){const [state,setState]=useState<DemoState>(()=>parseDemoState(location.search));useEffect(()=>{const h=()=>setState(parseDemoState(location.search));addEventListener("popstate",h);return()=>removeEventListener("popstate",h)},[]);const go=(next:DemoState)=>{history.pushState({},"",demoUrl(next));setState(next)};return{state,go}}
export default function DemoOnboarding({state,go}:{state:DemoState;go:(s:DemoState)=>void}){const[product,setProduct]=useState(state.productInput);const[audience,setAudience]=useState(state.audienceInput);const[unsupported,setUnsupported]=useState(false);if(state.view==="scope")return null;const step=(view:DemoView)=>go({...state,view});return <section className="border-y border-line bg-gradient-to-b from-paper to-surface"><div className="max-w-3xl mx-auto px-6 py-14"><div className="text-[11px] uppercase tracking-[0.18em] text-muted font-semibold mb-2 text-center">Keyword search demo</div><h2 className="font-display font-bold text-ink text-2xl mb-6 text-center">{state.view==="product"?"What product or company are you promoting?":state.view==="audience"?"Who is your target customer?":"Which market are you targeting?"}</h2><div className="rounded-2xl border border-line bg-surface p-5">
{state.view==="product"&&<form onSubmit={e=>{e.preventDefault();const domain=inferDomain(product);if(!domain){setUnsupported(true);return}go({view:"audience",domain,productInput:product.trim().slice(0,120),audienceInput:""})}} className="space-y-3"><input value={product} onChange={e=>{setProduct(e.target.value);setUnsupported(false)}} placeholder="e.g. sun cream or soccer equipment" className="w-full border border-line rounded-xl px-4 py-3" autoFocus/>{unsupported&&<p className="text-sm text-amber-700">This demo supports sunscreen and soccer equipment only.</p>}<button className="px-5 py-2.5 rounded-lg bg-accent text-white font-semibold">Continue</button></form>}
{state.view==="audience"&&state.domain&&<div><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Describe the target customer" className="w-full border border-line rounded-xl px-4 py-3"/><div className="flex flex-wrap gap-2 mt-3">{audienceSuggestions[state.domain].map(x=><button key={x} onClick={()=>setAudience(x)} className="text-sm border border-line rounded-full px-3 py-1.5 hover:border-accent">{x}</button>)}</div><div className="flex gap-3 mt-5"><button onClick={()=>step("product")} className="text-sm text-muted">Back</button><button disabled={!audience.trim()} onClick={()=>go({...state,view:"market",audienceInput:audience.trim().slice(0,120)})} className="px-5 py-2.5 rounded-lg bg-accent text-white disabled:opacity-40">Continue</button></div></div>}
{state.view==="market"&&<div className="grid sm:grid-cols-2 gap-3">{markets.map(m=><button key={m.id} onClick={()=>go({...state,view:"scope",market:m.id})} className="border border-line rounded-xl px-4 py-4 text-left hover:border-accent font-medium">{m.label}</button>)}<button onClick={()=>step("audience")} className="text-sm text-muted text-left mt-2">Back</button></div>}
</div></div></section>}
